### ISSUE TITLE
jlreq.cls+upLaTeXの組み合わせでは、寿司など一部の絵文字がエラー・警告も出ずに欠落する

### ISSUE THREAD

**Issue by kmuto** [zr-tex8r/BXcoloremoji#1]
関連 abenori/jlreq/issues/44

kcatcodeで欧文化されていることによる問題とのことですが、sty側で対応できるならそのほうがよいのでは？という @abenori さんのご意見をいただいてこちらに報告いたします。

luatexでは問題ない、ucsコード指定マクロのほうならupLaTeXでも問題ない、自前でkcatcodeを変えることでも対応できる、という状況なので困窮しているというほどではありません。

**Comment by zr-tex8r** [comment]
a2f1bbb2b6b4e2743191b356a88478503f20ece5 で対処してみました。

  * upLaTeXの場合も（pLaTeX/pdfLaTeXと同様に）「絵文字範囲の文字で欧文扱いになっているもの」を`\coloremoji`で使えるようにした。
      * bxcoloremoji読込時点で「絵文字範囲の文字で欧文扱いになっているもの」が対象になる。後からkcatcodeを変えた場合は対象外。
  * `\coloremoji`の引数中の欧文扱いの文字が“未実装”の場合、従来は単に無視されていたが、警告を出すようにする。
  * エンジンがupLaTeXで「絵文字範囲の文字で欧文扱いになっているもの」が存在して、かつutf8入力エンコーディングが有効になっていない場合は警告を出す。
      * pLaTeX/pdfLaTeXでは従来からエラーが出る仕様。
      * `\usepackage[utf8]{inputenc}`するとutf8入力エンコーディングが有効になるのだが、TeX Live 2018のLaTeXではデフォルトでutf8入力エンコーディングが有効になることに注意。

**Comment by kmuto** [comment]
動作確認しました、ありがとうございます！

**Comment by zr-tex8r** [comment]
そのままの実装でリリースしました。(v0.7)
