### ISSUE TITLE
スキントーン単体では絵文字が出ない

### ISSUE THREAD

**Issue by emojifreak** [zr-tex8r/BXcoloremoji#2]
Twitter Emoji自体はスキントーン単体の絵文字データを配布していますが、bxcoloremoji.styだと

```
\documentclass{minimal}
\usepackage{bxcoloremoji}

\begin{document}
\coloremoji*{🏻}\\
\coloremoji*{🏼}\\
\coloremoji{🏽}\\
\coloremoji{🏾}\\
\coloremoji{🏿}
\end{document}
```

というファイルで `Package bxcoloremoji Warning: Lone combining character found` と言って絵文字を出してくれません。他の絵文字フォントだとだいたい出してくれます。また https://github.com/twitter/twemoji/blob/master/src/test/preview-svg.html にある絵文字シーケンスを latex に変換したファイルを https://github.com/emojifreak/All-Emoji-by-HarfTeX-and-LuaTeX-ja/blob/master/really-full-emoji-by-harftex.tex に作ったのでテストなどに使えるようなら使って下さい。

**Comment by zr-tex8r** [comment]
対応しました → 758c0b527d49e8b06675773ed7111ef0cd6b7e8d 

* Unicodeの規定ではskin tone modifierはそれ自体がEmojiであり単体でで絵文字表示になるのが正常挙動なので警告は出さない。（UTR51によると孤立したregion indicatorは異常らしい。）

**Comment by emojifreak** [comment]
ありがとう御座います。このイシュー閉じます
