### ISSUE TITLE
\coloremojiと他の絵文字フォントを混在させると絵文字が消える？？

### ISSUE THREAD

**Issue by emojifreak** [zr-tex8r/BXcoloremoji#3]
以下のファイルをlualatexでコンパイルするとbxc2.pdfという期待通りのPDFができますが

```
\documentclass{minimal}
\usepackage{bxcoloremoji}

\font\fontA={[./TwemojiMozilla.ttf]:+colr;+ccmp;+dist;}
\font\fontB={name:Segoe UI Emoji:+colr;+ccmp;+dist;}

\begin{document}
  {\fontA ☃}{\fontB ☃}\\
  {\fontA 😀}{\fontB 😀}\\
\end{document}
```

\coloremojiコマンドを使って

```
\documentclass{minimal}
\usepackage{bxcoloremoji}

\font\fontA={[./TwemojiMozilla.ttf]:+colr;+ccmp;+dist;}
\font\fontB={name:Segoe UI Emoji:+colr;+ccmp;+dist;}

\begin{document}
{\coloremoji{☃}}  {\fontA ☃}{\fontB ☃}\\
{\coloremoji{😀}}  {\fontA 😀}{\fontB 😀}\\
\end{document}
```

というファイルをコンパイルするとbxc1.pdfというファイルができて、一部の絵文字が消えてしまう現象が観察されたので報告いたします。bxcoloremojiはリリースの欄にある0.9です。他の関連パッケージはTeXLive最新のはずです
[bxc1.pdf](https://github.com/zr-tex8r/BXcoloremoji/files/3840063/bxc1.pdf)
[bxc2.pdf](https://github.com/zr-tex8r/BXcoloremoji/files/3840066/bxc2.pdf)

**Comment by zr-tex8r** [comment]
「画像出力（`\includegraphics`）と絵文字フォント出力を併用したときに起こる不具合」であって、bxcoloremojiは直接は無関係のようです。
（つまりbxcoloremojiの側で対処する問題ではない。）

例えば、次のような文書を作ります。

```latex
\documentclass{article}
\usepackage{graphicx}
\font\fontB={name:Segoe UI Emoji:+colr;+ccmp;+dist;}
\begin{document}
% example-image-1x1.pdf はテフライブにある(mmeパッケージ)
\includegraphics[width=20pt]{example-image-1x1.pdf}% (*)
{\fontB ^^^^2603}!{\fontB ^^^^^^01f986}
\end{document}
```

(*)の行（画像読込）がない場合の出力（[test-without-image.pdf](https://github.com/zr-tex8r/BXcoloremoji/files/3930440/test-without-image.pdf)）は正常です.。

一方で、(*)の行がある場合の出力（[test-with-image.pdf](https://github.com/zr-tex8r/BXcoloremoji/files/3930437/test-with-image.pdf)）では、最初の絵文字’（:snowman:）以降のテキストが消えています。よく見ると、下部に出るはずのページ番号「1」が上の方の変な位置に出ています。つまり、:snowman:の後の出力の「位置が大きくずれてしまっている」のだと考えられます。

**Comment by emojifreak** [comment]
うああ…😱
どうもありがとうございます。
Contextの問題だとすると、contextで問題起こす例を作るのが（自分には）難しそう。
mode=harfでどうなるのか後で見てみます（mode=harfで問題起きないなら多分contextの問題なので）

**Comment by zr-tex8r** [comment]
luaotfloadは（ConTeXtのコードを使っているとはいえ）LaTeXの世界のもののはず（latex3のリポジトリにあるわけだし）だから、とりあえずluaotfloadの方に投げてみるのがいいかも。

**Comment by emojifreak** [comment]
基本、仰る通りだと思いますが、💔の片割れが黒く描画されるのとかSVG入りオープンタイプの扱いの不具合はcontext由来だったので一手間で調べられることは見てから報告したいと思います（いまスマホしか触れないですし）

**Comment by emojifreak** [comment]
Reported as https://github.com/latex3/luaotfload/issues/124

**Comment by emojifreak** [comment]
この件の根本にあったluaotfloadのイシューは閉じられているのでそっちのほうは直ったようです

**Comment by emojifreak** [comment]
luaotfloadの問題はイシューが閉じられているにも関わらず治ってないからだめですな…😂

**Comment by emojifreak** [comment]
{mode=harf}でフォントを読めばこのイシューで述べた問題は起きなくなりました（最新のlualatex-dev + luaotfload 3.12 + git cloneしたbxcoloremoji) 。なお +colr でフォントを読むと相変わらずだめです（このイシューを閉じるタイミングはお任せします）

**Comment by zr-tex8r** [comment]
とりあえず、bxcoloremojiとは直接関係ないのでクローズします。

**Comment by emojifreak** [comment]
@zr-tex8r ご対応と例作成ありがとうございました。
