### ISSUE TITLE
Package bxcoloremoji Error: Package 'graphicx' is not loaded.

### ISSUE THREAD

**Issue by emojifreak** [zr-tex8r/BXcoloremoji#4]
```latex
\documentclass{article}
\usepackage{bxcoloremoji}
\begin{document}
\end{document}
```

を`latex` または `platex`または`uplatex`でコンパイルすると表題のエラーが出て怒られます。`pdflatex`, `xelatex`,`lualatex`では怒られませんでした。自分でgraphicx.styを読むことにして `\usepackage{graphicx}` をbxcoloremojiの前に置くと今度は 

```
LaTeX Error: Cannot determine size of graphic in emoji_images/twemoji-pdf/A9.pdf
```

と怒られて、`\usepackage[dvipdfmx]{graphicx}` とすると怒られなくなりました

**Comment by zr-tex8r** [comment]
graphicxパッケージの自動読込は、PDF出力のエンジン（pdflatexなど）では行われますがDVI出力のエンジン（latexやplatexなど）では行われません。その理由は **「DVI出力の場合は適切なドライバオプションを指定する必要があるが、それが何であるかはユーザしか知らない」** からです。

このため、DVI出力のエンジンでgraphicxが読み込まれていない場合は「graphicxが読み込まれていない」というエラーを出して、ユーザにgraphicxを適切に（つまり、正しいドライバオプションを伴って）読み込んでもらうしか対処のしようがないわけです。

**Comment by emojifreak** [comment]
ありがとうございます🙏うけたまわりました
